### ISSUE TITLE
Why is epsilon=12/255 on CIFAR-10 linf?

### ISSUE THREAD

**Issue by dssrgu** [ash-aldujaili/blackbox-adv-examples-signhunter#2]
Hi, thanks for the interesting work and code!

While trying to run your code, I found that the epsilon bound is set to 12/255 instead of 8/255 on CIFAR-10 linf threat models (for example, on blackbox-adv-examples-signhunter/src/config-jsons/cifar10_shc_linf_config.json). But isn't 8/255 bound much more common, even on black-box attacks?  The main paper says that the bound setting is from (Ilyas et al., 2019), while that work also uses epsilon=8/255 on CIFAR-10 linf threat models.

Thank you.

**Comment by ash-aldujaili** [comment]
Hi @dssrgu, thank you for your question and interest.

If you look at Table 4 (page 20) from Ilyas et al. (https://openreview.net/pdf?id=BkMiWhR5K7), the allowed perturbation for CIFAR10-linf is set to 0.05 for images in [0,1]. This is 0.05 * 255 = 12.

Hope this answers your question.

Best,
