### ISSUE TITLE
crit_queries and loss_queries

### ISSUE THREAD

**Issue by Kira0096** [ash-aldujaili/blackbox-adv-examples-signhunter#3]
Hi, thanks for the repo!

I have a question about the query metric. For all experiments, 'crit_queries' and 'loss_queries' are counted separately. But they both require querying the victim model. 

Is there any overlap between the two metrics or do I add the two metrics up to get the total query number?

**Comment by ash-aldujaili** [comment]
Hi @Kira0096,

Thank you for your interest and the question. Please find the response below.

The query assumption here is that the oracle returns the class probabilities from which the attacker can compute L (loss_queries) and C(crit_queries), and use one or both of them for the attack. The separation between these types of queries in the code was done to understand how each of the attack methods (e.g., NES, Bandits, SignHunter) spend queries before crafting an adversarial example. You can think of C calls as early stopping checks if the adversarial attack is successful; these C calls are readily presented to you when you perform the next batch of L calls. 

With regard to reporting the query metric, you should just report the "loss_queries". This is in line with the evaluation protocol of Ilyas et al, ICLR’19 (see Alg. 3 in https://arxiv.org/pdf/1807.07978.pdf, where early stopping check (Alg 3, Line 5) is not considered as part of the query metric for the reasons discussed above). 

Hope the above helps.
