### ISSUE TITLE
What is the difference between sgn_t and the sign of true gradient?

### ISSUE THREAD

**Issue by machanic** [ash-aldujaili/blackbox-adv-examples-signhunter#5]
I am confused that the sign-bits-based gradient `sgn_t` in your paper  found by divide-and-conqure method, which flip half / quarter to check whether the loss decreased.
Does it different from the sign of true gradient?
In other words, what is difference between sign(true_gradient) and sign bits gradient found by divide-and-conqure?
Are the values inside two gradient maps different?
Thank you!

**Comment by ash-aldujaili** [comment]
Our goal is to match `sign(true_gradient)`, but remember that the true gradient measures the infinitesimal change in loss function (i.e., as eps -> 0). `sgn_t` estimation is based on finite-difference so if the loss function is not that smooth around \eps, it is not surprising that they will be different.

Comparisons of the true gradient vs sgn_t can be found in Fig 7-9 of the paper.
