### ISSUE TITLE
Why the perturbation with its value equals the maximum bound of Linf and L2 attack should be used in update? 

### ISSUE THREAD

**Issue by machanic** [ash-aldujaili/blackbox-adv-examples-signhunter#6]
I wonder the use of maximum bound of Linf and L2 attack in the update is the best choice?
 Can it change to a value inside the `[-eps, eps]` interval? (smaller than `eps`)  Would it possible be better?

**Comment by ash-aldujaili** [comment]
Hi @machanic, your question above is not an issue. Please reserve issues for problems in the code.

Feel free to e-mail with your doubts on the algorithm, but here is the rationale:

Yes, other configuration of the update step could be better but to reduce our sensitivity to this hyperparameter, we just set it to the bound defined by the threat model. With this, the algorithm become hyper-parameter free.
